name = "Grafana Alloy"
grammar = "alloy"
path_suffixes = ["alloy"]
line_comments = ["// "]
tab_size = 2
autoclose_before = ";:.,=}]) \n\t\""
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "/*", end = " */", close = true, newline = true, not_in = ["string", "comment"] },
]
block_comment = { start = "/*", prefix = "", end = "*/", tab_size = 2 }
collapsed_placeholder = " /* ... */ "
